-- MySQL Script generated by MySQL Workbench
-- 09/20/17 02:11:23
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema id2975095_srvicos
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema id2975095_srvicos
-- -----------------------------------------------------

USE `id2975095_srvicos` ;

-- -----------------------------------------------------
-- Table `id2975095_srvicos`.`Acl`
-- -----------------------------------------------------
CREATE TABLE  `id2975095_srvicos`.`Acl` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '',
  `descricao` VARCHAR(15) NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `id2975095_srvicos`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE  `id2975095_srvicos`.`Usuario` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '',
  `nome` VARCHAR(250) NOT NULL COMMENT '',
  `email` INT NOT NULL COMMENT '',
  `cpf` CHAR(11) NOT NULL COMMENT '',
  `uf` CHAR(2) NOT NULL COMMENT '',
  `cidade` VARCHAR(50) NOT NULL COMMENT '',
  `cep` CHAR(8) NOT NULL COMMENT '',
  `bairro` VARCHAR(250) NOT NULL COMMENT '',
  `endereco` VARCHAR(250) NOT NULL COMMENT '',
  `idAcl` INT UNSIGNED NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  UNIQUE INDEX `email_UNIQUE` (`email` ASC)  COMMENT '',
  UNIQUE INDEX `cpf_UNIQUE` (`cpf` ASC)  COMMENT '',
  INDEX `fk_Usuario_Acl1_idx` (`idAcl` ASC)  COMMENT '',
  CONSTRAINT `fk_Usuario_Acl1`
    FOREIGN KEY (`idAcl`)
    REFERENCES `id2975095_srvicos`.`Acl` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `id2975095_srvicos`.`Telefone`
-- -----------------------------------------------------
CREATE TABLE  `id2975095_srvicos`.`Telefone` (
  `idTelefone` INT NOT NULL COMMENT '',
  PRIMARY KEY (`idTelefone`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `id2975095_srvicos`.`Servico`
-- -----------------------------------------------------
CREATE TABLE  `id2975095_srvicos`.`Servico` (
  `id` INT UNSIGNED NOT NULL COMMENT '',
  `descricao` VARCHAR(250) NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  UNIQUE INDEX `descricao_UNIQUE` (`descricao` ASC)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `id2975095_srvicos`.`Servico_Usuario`
-- -----------------------------------------------------
CREATE TABLE  `id2975095_srvicos`.`Servico_Usuario` (
  `Servico_id` INT UNSIGNED NOT NULL COMMENT '',
  `Usuario_id` INT UNSIGNED NOT NULL COMMENT '',
  INDEX `fk_Prestacao_Servico_Servico1_idx` (`Servico_id` ASC)  COMMENT '',
  INDEX `fk_Prestacao_Servico_Usuario1_idx` (`Usuario_id` ASC)  COMMENT '',
  CONSTRAINT `fk_Prestacao_Servico_Servico1`
    FOREIGN KEY (`Servico_id`)
    REFERENCES `id2975095_srvicos`.`Servico` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Prestacao_Servico_Usuario1`
    FOREIGN KEY (`Usuario_id`)
    REFERENCES `id2975095_srvicos`.`Usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `id2975095_srvicos`.`Prestacao_Servico`
-- -----------------------------------------------------
CREATE TABLE  `id2975095_srvicos`.`Prestacao_Servico` (
  `id` INT UNSIGNED NOT NULL COMMENT '',
  `comentario` TINYTEXT NULL COMMENT '',
  `valor` FLOAT NULL COMMENT '',
  `status` TINYINT(1) NOT NULL COMMENT '',
  `Servico_id` INT UNSIGNED NOT NULL COMMENT '',
  `Usuario_id` INT UNSIGNED NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `fk_Prestacao_Servico_Servico2_idx` (`Servico_id` ASC)  COMMENT '',
  INDEX `fk_Prestacao_Servico_Usuario2_idx` (`Usuario_id` ASC)  COMMENT '',
  CONSTRAINT `fk_Prestacao_Servico_Servico2`
    FOREIGN KEY (`Servico_id`)
    REFERENCES `id2975095_srvicos`.`Servico` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Prestacao_Servico_Usuario2`
    FOREIGN KEY (`Usuario_id`)
    REFERENCES `id2975095_srvicos`.`Usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `id2975095_srvicos`.`Conversa`
-- -----------------------------------------------------
CREATE TABLE  `id2975095_srvicos`.`Conversa` (
  `id` INT UNSIGNED NOT NULL COMMENT '',
  `mensagem` TEXT NOT NULL COMMENT '',
  `data` DATE NOT NULL COMMENT '',
  `status` TINYINT(1) NOT NULL COMMENT '',
  `Usuario_id` INT UNSIGNED NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `fk_Conversa_Usuario_idx` (`Usuario_id` ASC)  COMMENT '',
  CONSTRAINT `fk_Conversa_Usuario`
    FOREIGN KEY (`Usuario_id`)
    REFERENCES `id2975095_srvicos`.`Usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
